/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package openEHR_GUI;

import Elements.TeleconsultationActors;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import openEHR_CONTROL.CreateTeleconsultationFile;
import openEHR_DAO.TeleconsultationFileAccess;

/**
 *
 * @author vinicius
 */
public class TeleconsultationElements extends javax.swing.JPanel {

    final JTabbedPane jtp;
    List<ArchetypeTypeTab> panels;

    public TeleconsultationElements() {
        initComponents();
        JPanel panel2 = new JPanel();
        jButton1.setText("Create System Configuration");
        panel2.add(jButton1);
        TeleconsultationFileAccess tfa = new TeleconsultationFileAccess();
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        jtp = new JTabbedPane();
        this.add(jtp);
        this.add(panel2);
        JPanel panel = null;
        panels = new ArrayList<>();

        for (TeleconsultationActors t : tfa.getTactors()) {
            panels.add(new ArchetypeTypeTab(t.getName(), t.getTeleproper()));

        }
        for (ArchetypeTypeTab att : panels) {
            jtp.add(att.getName(), att);
        }
        jtp.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                SwingUtilities.windowForComponent(jtp).pack();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 410, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<DefaultListModel> model = new ArrayList<>();
        for (ArchetypeTypeTab atat : panels) {
     
            model.add(atat.getModel2()); // PAREI AQUI DEU ERRO            
        }
        CreateTeleconsultationFile.createFile(model);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
