/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package openEHR_GUI;

import Utils.Log;
import java.awt.Component;
import javax.swing.BoxLayout;

/**
 *
 * @author vinicius
 */
public class MainFrame extends javax.swing.JFrame {

    TeleconsultationElements te;

    public MainFrame() {

        Log lg = new Log();
        te = new TeleconsultationElements();
        initComponents();


        setLayout(new BoxLayout(this.getContentPane(), BoxLayout.PAGE_AXIS));
        getContentPane().add(te);

        pack();
        /*
         * getContentPane().add(new ArchetypePane(new
         * File("/Users/vinicius/Dropbox/Importantes/OpenEHR - Archetype+RM
         * Splicer and
         * Editor/Repository/openehr/ehr/entry/observation/openEHR-EHR-OBSERVATION.anaesthetic.v1draft.xml")));
         * pack();
         */
        /*
         * JPanel jp = new ArchetypePane(new
         * File("/Users/vinicius/Dropbox/Importantes/OpenEHR - Archetype+RM
         * Splicer and
         * Editor/Repository/openehr/ehr/entry/observation/openEHR-EHR-OBSERVATION.anaesthetic.v1draft.xml"));
         * setLayout(new BorderLayout()); getContentPane().add(jp);
         */


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
            System.out.println(this.getContentPane().getComponents()[0].getName());
        for (Component Components : this.getContentPane().getComponents()) {
            if (Components instanceof ArchetypeTypeTab) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
